version: '3'

services:
  web:
    container_name: control-center
    image: vatsca/apache
    ports:
        - 8000:80
    extra_hosts:
        - "host.docker.internal:host-gateway"
    volumes:
      - ./:/var/www/html