version: '3'

services:
  web:
    container_name: control-center
    image: vatsca/apache:7.4
    ports:
        - 8000:80
    extra_hosts:
        - "host.docker.internal:host-gateway"
    volumes:
      - ./:/var/www/html
    restart: unless-stopped
    command: sh /var/entrypoint.sh "* * * * * cd /var/www/html && php artisan schedule:run >> /dev/null 2>&1"