version: '3'

services:
  web:
    container_name: control-center
    image: vatsca/apache:php-7.4
    ports:
        - 5010:80
        - 5011:443
    extra_hosts:
        - "host.docker.internal:host-gateway"
    volumes:
      - ./:/var/www/html
      - ./apache:/var/www/logs